### ISSUE TITLE
在同步用户数据的时候出现问题

### ISSUE THREAD

**Issue by tangzicheng** [Hanson/laravel-admin-wechat#1]
查看了一下，先用cgi/user/get获取用户list,再用batchget去获取详细信息，但是batchget一次只能拉100，所以需要对前面的list进行处理

**Comment by Hanson** [comment]
确实有这样的问题，今天会修复一下

**Comment by Hanson** [comment]
fixed in https://github.com/Hanson/laravel-admin-wechat/commit/bd55039a113ec17386198e59446a9bef70f778de
