### ISSUE TITLE
ImportUserJob

### ISSUE THREAD

**Issue by tangzicheng** [Hanson/laravel-admin-wechat#2]
在wechat user填充到数据库的时候，Carbon::parse($user['subscribe_time'])->toDateTimeString()  这个函数好像要报错，我换成'subscribed_at' => $user['subscribe'] ? date('Y-m-d H:i:s', $user['subscribe_time']): null好像就没有问题了，您可以确认一下

**Comment by Hanson** [comment]
报错是报什么错误？

**Comment by tangzicheng** [comment]
Carbon::parase(XXXXXXX)

XXXXX为获取到的subscribe_time, 返回的是时间戳，所以会报parse error的错误。

我看了Carbon的手册, 

parse好像不处理15553458之类的时间戳



tangk@wolink.com.cn
 
From: Hanson
Date: 2020-02-19 15:13
To: Hanson/laravel-admin-wechat
CC: tangzicheng; Author
Subject: Re: [Hanson/laravel-admin-wechat] ImportUserJob (#2)
报错是报什么错误？

**Comment by Hanson** [comment]
@tangzicheng 应该是你 carbon 版本问题，版本 为 2 就能支持了，我兼容一下吧

查看版本 `composer show nesbot/carbon`

**Comment by Hanson** [comment]
fixed https://github.com/Hanson/laravel-admin-wechat/commit/7003d457db40bba9e7133448ca6b887ed7162485
