### ISSUE TITLE
关于使用开箱小程序登录接口的问题

### ISSUE THREAD

**Issue by kendling** [Hanson/laravel-admin-wechat#3]
原谅我是新手。

按教程配置下来，调用 `/api/wechat/mini/login` 正确返回 token 了。
但使用 token 调用 `/api/wechat/mini/decrypt-user-info` 接口时一直失败。

尝试了以下方法：
1、Header 带 `authorization` 参数，放上 `token`
2、post 带 `token` 参数，放上 `token` 去掉 bearer 前缀
3、queryString 带 `token` 参数，放上 `token` 去掉 bearer 前缀

期间遇到了各种各样的问题，如：
1、服务器 500 错误
2、无法找到 login 路由
3、Argument 3 passed to Lcobucci\JWT\Signer\Hmac::doVerify() must be an instance of Lcobucci\JWT\Signer\Key

花了几天时间调试，最后还是在第三个错误信息里面找到解决办法。

调试+翻看 https://github.com/tymondesigns/jwt-auth 的文档。

最终确定了原因：JWT 模块缺少配置。

复制 jwt-auth 模块下的 `config/config.php` 文件到项目的 `config/jwt.php` ，并且运行 `php artisan jwt:secret` 命令生成 `JWT_SECRET` 并写入 `.env` 文件。

配置完成后重新调用 `/api/wechat/mini/login` 和 `/api/wechat/mini/decrypt-user-info` 发现已经正确跑起来了。

**Comment by Hanson** [comment]
感谢，使用这个 jwt 的确需要跑这个命名，是我忽略了

**Comment by kendling** [comment]
另外 `wechat_user` 表的 `user_id` 字段是怎么关联的？

我 grep 了一下，`laravel-admin-wechat` 里目前并没有使用这个字段。

**Comment by Hanson** [comment]
本扩展没有实现，因为这是个业务问题

例如一个 user 可以使用公众号和小程序，对应就有两个 wechat_user 

所以留有的这个字段是交给大家发挥

**Comment by kendling** [comment]
> 本扩展没有实现，因为这是个业务问题
> 
> 例如一个 user 可以使用公众号和小程序，对应就有两个 wechat_user
> 
> 所以留有的这个字段是交给大家发挥

了解，感谢解答

**Comment by SamHz** [comment]
此扩展只有小程序快捷登录API吗？请问公众号的有吗？
